name: bajulan_mobile
description: "A new Flutter project for Kampung Adat Bajulan."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- TAMBAHAN WAJIB ---
  get: ^4.6.6              # Untuk State Management (Controller) yang kita bahas
  google_fonts: ^6.1.0     # Agar lebih mudah panggil Plus Jakarta Sans tanpa download manual
  http: ^1.1.0             # Untuk koneksi ke database Laravel kamu nanti

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- SETUP ASSET ---
  # Pastikan kamu buat folder 'assets/images/' di root project
  assets:
    - assets/images/

#  # --- SETUP FONT (Sesuai Design System kamu) ---
#  fonts:
#    - family: Plus Jakarta Sans
#      fonts:
#        - asset: fonts/PlusJakartaSans-Regular.ttf
#        - asset: fonts/PlusJakartaSans-Medium.ttf
#          weight: 500
#        - asset: fonts/PlusJakartaSans-SemiBold.ttf
#          weight: 600
#        - asset: fonts/PlusJakartaSans-Bold.ttf
#          weight: 700